server:
  port: 8080

spring:
  #redis ??
  redis:
    host: j8b207.p.ssafy.io
    port: 3301
    password: ns

  application:
    name: mything


  servlet:
     multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  #??? ??
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # ??? ?? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/mything-test?serverTimezone=Asia/Seoul
    url: jdbc:mysql://j8b207.p.ssafy.io:3300/mything?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: ns
    password: ns

  # JPA ??
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
##    show-sql: true
#    hibernate:
#      ddl-auto: update
#      format_sql: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 9eec0e493dbf3db1f50e9930111e3715
            client-secret: FCwY0l62aS1ulyNDCRl3CofAY0XZ8lrF
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            redirect-uri: http://j8b207.p.ssafy.io/api/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace


cloud:
  aws:
    credentials:
      accessKey: AKIA6DQ7N6XNSJA5CXSN      # AWS IAM AccessKey 적기
      secretKey: M6u8mYgKSquwYuRzXDAOhv+j9RhnHNMOQ/zLrAdP   # AWS IAM SecretKey 적기
    s3:
      bucket: b207bucket    # ex) marryting-gyunny
#      dir: /blur # ex) /gyunny
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  secretKey: SN5OUPJANIZLB/hZ1q7CsJbHvvuZ5xahm6DZMxTZyDI=

  access:
    expiration: 36000000000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
#    header: Authorization-refresh
