# Generated by Django 4.1.7 on 2023-03-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('perfume_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('image_url', models.TextField()),
                ('notes', models.CharField(max_length=255)),
                ('info', models.TextField()),
            ],
            options={
                'db_table': 'perfume',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('perfume_id', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'review_db',
            },
        ),
    ]
