# Generated by Django 4.1.7 on 2023-03-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='perfume_no',
            field=models.IntegerField(),
        ),
    ]
