package com.project.mything.perfume.entity;

public enum CategoryName {
    CITRUS, FRUITS_VEGETABLES_AND_NUTS, FLOWERS, WHITE_FLOWERS, GREENS_HERBS_AND_FOUGERES, SPICES, SWEETS_AND_GOURMAND,
    WOODS_AND_MOSSES, RESINS_AND_BALSAMS, MUSK_AMBER_AND_ANIMAL, NATURAL_SYNTHETIC_POPULAR_AND_WEIRD
}
