server:
  port: 8080
jwt:
  secret: SN5OUPJANIZLB/hZ1q7CsJbHvvuZ5xahm6DZMxTZyDI=
  access-expiration-in-ms: 600000
  refresh-expiration-in-ms: 1209600000
spring:
  #redis ??
  redis:
    host: j8b207.p.ssafy.io
    port: 3301
    password: ns

  application:
    name: mything

  #??? ??
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # ??? ?? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/mything-test?serverTimezone=Asia/Seoul
    url: jdbc:mysql://j8b207.p.ssafy.io:3300/mything?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: ns
    password: ns

  # JPA ??
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 9eec0e493dbf3db1f50e9930111e3715
            client-secret: FCwY0l62aS1ulyNDCRl3CofAY0XZ8lrF
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace


